### PR TITLE
Darian quiz intergration

### PR DESCRIPTION
**Pull request by DarianRushworth**
On Merge of all major components, I did a sweep to see if functionality was correct and firing properly across server and client.
Whilst doing this I saw the opportunity to create the "random" exercises category.
_**What has been implemented:**_

- A new page with protected route "/exercise/random"
- In state all the questions are fetched from the backend
-As much as the rendering of each question was very simple as of the two completed components already:

1. Quiz Cards
2. Quiz Codes

- Thanks to Diego's Logic on the elements page switching between the components has never been easier.

### CODE REVIEW

**Review by StephBerg86 — APPROVED** [review]
Whoohoo random is also working! So cool how you did this logic. impressive.

**Review by DiegoOTdC — COMMENTED** [review]
Hi man! Great way to make this work! Just 1 little thing, in the store/exercise/actions, the first dispatch needs to be dispatch(appLoading()) -> you're dispatching appDoneLoading from the start. For the rest really nice man!

**Comment by DarianRushworth** [comment]
> Hi man! Great way to make this work! Just 1 little thing, in the store/exercise/actions, the first dispatch needs to be dispatch(appLoading()) -> you're dispatching appDoneLoading from the start. For the rest really nice man!

Great find, edit complete and successful.

**Review by DiegoOTdC — APPROVED** [review]
👍

**Pull request merged**
