### PR TITLE
Darian cards quiz

### PR DESCRIPTION
**Pull request by DarianRushworth**
###
_**What we wanted to accomplish:**_
With our level 1 questions being multiple choice we wanted to display them on a card, with the user being able to choose any of the given answers. If he/she makes a decision there should be a reaction to tell the user if their choice was correct or not.
_**What I managed to accomplish:**_
On entrance the component doesn't load so a refresh is needed and it will display, fix in the next update. Displays a card with the question and the four optional answers, the answers are consistently shuffled so the user cannot guess the order. On click on the correct answer will display the card as green, all other answers will display the card red.
After completing the two questions the user is pushed back to the exercises page, until we can setup the QuizCode component.

### CODE REVIEW

**Review by DiegoOTdC — COMMENTED** [review]
Looks great Darian! Great way to randomize it like that. I am just wandering why you are pushing to the homepage after you finish 2 exercises? I guess because you finish level 1 then, but after that it will go straight to level 2 and switch the QuizCards component for the QuizCode component. So no need to push to homepage I think... Also I think we both send that the exercise is completed in a different way I believe, to a different router on the backend... Not sure if that's correct, also not sure which one is correct! But we can figure that out later and correct it if needed in another pull request!

**Comment by DarianRushworth** [comment]
> Looks great Darian! Great way to randomize it like that. I am just wandering why you are pushing to the homepage after you finish 2 exercises? I guess because you finish level 1 then, but after that it will go straight to level 2 and switch the QuizCards component for the QuizCode component. So no need to push to homepage I think... Also I think we both send that the exercise is completed in a different way I believe, to a different router on the backend... Not sure if that's correct, also not sure which one is correct! But we can figure that out later and correct it if needed in another pull request!

So today I am working on the logic a bit with switching from level 1 to level 2, as when I complete Level 1, it just starts the quiz questions form the beginning. With the dispatching to different router in the backend, I rate we keep it like this as my router for level 1 doesn't take time into consideration, where for your router it does as level 2 has the time constraint. Could probably scale down to one router, but right now i rate we get the MVP setup and then start cleaning and scaling where we can. Great feedback Diego!!

**Review by StephBerg86 — APPROVED** [review]
Looks good, and I agree with Diego.

**Comment by DarianRushworth** [comment]
Need to adjust the actions/reducer/selector, as the questions were going into the exercises, and making them a bit confused. Made a new slice in the reducer under exercises, as questions.
Now we can collect the exercises from exercises.exercise and the questions from exercises.questions.

**Review by DiegoOTdC — APPROVED** [review]
Good thinking!

**Pull request merged**
